**Basic Python**

**1. Split this string**

In [7]:
s = "Hi There!"

In [10]:
s = "Hi There!"
s = s.split()

print(s)

['Hi', 'There!']


**2. Use .format() to print the following string**

**Output should be: The diameter of Earth is 12742 kilometers.**

In [11]:
planet = "Earth"
diameter = 12742

In [12]:
print("The diameter of the {} is {} kilometers.".format(planet , diameter))

The diameter of the Earth is 12742 kilometers.


**3. In this nest dictionary grab the word "hello"**

In [13]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [14]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

print(d['k1'][3]['tricky'][3]['target'][3])


hello


**Numpy**


In [15]:
import numpy as np

**4.1 Create an array of 10 zeros?**

**4.2 Create an array of 10 fives?**

In [16]:
#4.1 Create an array of 10 zeros
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)

An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [17]:
#4.2 Create an array of 10 fives
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)

An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


**5. Create an array of all the even integers from 20 to 35**

In [18]:
array=np.arange(20,35,2)
print("Array of all the even integers from 20 to 35")
print(array)

Array of all the even integers from 20 to 35
[20 22 24 26 28 30 32 34]


**6. Create a 3x3 matrix with values ranging from 0 to 8**

In [19]:
a =  np.arange(0, 9).reshape(3,3)
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


**7. Concatenate a and b**

**a = np.array([1, 2, 3]), b = np.array([4, 5, 6])**

In [20]:
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])
np.concatenate((a, b), axis=None)

array([1, 2, 3, 4, 5, 6])

**Pandas**

**8. Create a dataframe with 3 rows and 2 columns**

In [21]:
import pandas as pd

In [22]:
data = [450,260,370]
  
df = pd.DataFrame(data, columns=[''])
  
# print dataframe.
df

0  450
1  260
2  370

**9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023**

In [23]:
pd.date_range(start="2023-01-01",end="2023-02-10").tolist()

[Timestamp('2023-01-01 00:00:00', freq='D'),
 Timestamp('2023-01-02 00:00:00', freq='D'),
 Timestamp('2023-01-03 00:00:00', freq='D'),
 Timestamp('2023-01-04 00:00:00', freq='D'),
 Timestamp('2023-01-05 00:00:00', freq='D'),
 Timestamp('2023-01-06 00:00:00', freq='D'),
 Timestamp('2023-01-07 00:00:00', freq='D'),
 Timestamp('2023-01-08 00:00:00', freq='D'),
 Timestamp('2023-01-09 00:00:00', freq='D'),
 Timestamp('2023-01-10 00:00:00', freq='D'),
 Timestamp('2023-01-11 00:00:00', freq='D'),
 Timestamp('2023-01-12 00:00:00', freq='D'),
 Timestamp('2023-01-13 00:00:00', freq='D'),
 Timestamp('2023-01-14 00:00:00', freq='D'),
 Timestamp('2023-01-15 00:00:00', freq='D'),
 Timestamp('2023-01-16 00:00:00', freq='D'),
 Timestamp('2023-01-17 00:00:00', freq='D'),
 Timestamp('2023-01-18 00:00:00', freq='D'),
 Timestamp('2023-01-19 00:00:00', freq='D'),
 Timestamp('2023-01-20 00:00:00', freq='D'),
 Timestamp('2023-01-21 00:00:00', freq='D'),
 Timestamp('2023-01-22 00:00:00', freq='D'),
 Timestamp

**10. Create 2D list to DataFrame**

**lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]**

In [24]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [25]:
df = pd.DataFrame(lists, columns = ['', '',''])
print(df )

             
0  1  aaa  22
1  2  bbb  25
2  3  ccc  24
